# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application  #workflow name

on:  ## as the trigreess worklow on any push to the main branch or pull request
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest  # github provide conatiners 

    steps:
        # check out the code form the repository
    - uses: actions/checkout@v2
    # set up the python enviroment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3 # versoning chnage
      with:
        python-version: "3.12.5"
    # step 3 intsall dependencies    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
       
        pip install -r requirements.txt; 

    - name: Run tests
      run: |
        pytest

