# This workflow installs Python dependencies, runs tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:  # Triggers workflow on push or pull request to the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.12.5
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest
